config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                #   url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                #   url(r'^rush/$', TemplateView.as_view(template_name='pages/rush.html'), name='rush'),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include('texaslan.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('texaslan.events.urls', namespace='events')),
                  url(r'^', include('texaslan.home.urls', namespace='home')),
                  url(r'^go/', include('texaslan.go.urls', namespace='go')),
                  url(r'^notify/', include('texaslan.notify.urls', namespace='notify')),
                  url(r'^comments/', include('texaslan.comments.urls', namespace='comments')),
                  url(r'^applications/', include('texaslan.applications.urls', namespace='applications')),
                  url(r'^voting/', include('texaslan.voting.urls', namespace='voting')),
                  url(r'^notifications/', include('texaslan.notifications.urls', namespace='notifications')),
                  url(r'^slack/', include('django_slack_oauth.urls')),
                  url(r'^api/v1/', include('texaslan.api.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

texaslan/api/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from .views import AuthRegisterUser, Status, Event
from ..users.models import User
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    url(r'^jwt/login/', obtain_jwt_token),
    url(r'^jwt/refresh/', refresh_jwt_token),
    url(r'^jwt/verify/', verify_jwt_token),
    url(r'^jwt/register/', AuthRegisterUser.as_view()),
    url(r'^status/rush/', Status.as_view()),
    url(r'^events/', Event.as_view()),
]

texaslan/applications/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Application
    url(
        regex=r'^modify/$',
        view=views.ApplicationModifyView.as_view(),
        name='modify'
    ),
    url(
        regex=r'^$',
        view=views.ApplicationListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^(?P<id>\d+)/$',
        view=views.ApplicationDetailView.as_view(),
        name='detail'
    ),
]

texaslan/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

texaslan/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

texaslan/notify/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.NotifyView.as_view(),
        name='notify'
    ),
    url(
        regex=r'^me/$',
        view=views.NotifyMeView.as_view(),
        name='me'
    ),
]

texaslan/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^~update/slack-delete/$',
        view=views.delete_slack_token,
        name='slack-delete'
    ),
]

texaslan/applications/forms.py
from django import forms
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404

from .models import Application, Review
from texaslan.users.models import User
from texaslan.site_settings.models import SiteSettingService


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['question_1', 'question_2', 'question_3', 'question_4', 'question_5', 'question_6', 'question_7']

    def clean(self):
        application = self.save(commit=False)
        # This will validate if forms can be submitted or not

        if application.is_submitted:
            raise forms.ValidationError("Applications was already submitted")

        if not SiteSettingService.is_rush_open():
            raise forms.ValidationError("Application is late")

        if 'submit_btn' in self.data:
            application.is_submitted = True

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            application = self.save(commit=False)
            if application.is_submitted:
                for key, _ in self.fields.items():
                    self.fields[key].widget.attrs['readonly'] = True


RATING_CHOICES = (
    (1, "Strong No"),
    (2, "Weak No"),
    (3, "Neutral"),
    (4, "Weak Yes"),
    (5, "Strong Yes"),
)


class ReviewForm(forms.ModelForm):
    is_anon_comment = forms.BooleanField(label="Is anonymous comment?", required=False)

    class Meta:
        model = Review
        fields = ['comment', 'rating']

    def modify_review(self):
        print(self.data)
        if "is_anon_comment" not in self.data or self.data["is_anon_comment"] == 'off':
            application_id = int(self.data['application_id'])
            username = self.data['review_username']
            comment = self.cleaned_data['comment']
            rating = self.cleaned_data['rating']

            application = get_object_or_404(Application, pk=application_id)
            reviewer = get_object_or_404(User, username=username)
            try:
                review = Review.objects.get(application__pk=application_id, reviewer_user__pk=reviewer.pk)
            except Review.DoesNotExist:
                review = Review.objects.create()
            review.rating = rating
            review.comment = comment
            review.application = application
            review.reviewer_user = reviewer
            review.save()
        else:
            anon_review = Review.objects.create()
            anon_review.rating = self.cleaned_data['rating']
            anon_review.comment = self.cleaned_data['comment']
            anon_review.application = get_object_or_404(Application, pk=int(self.data['application_id']))
            anon_review.save()
        pass

texaslan/api/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from .serializers import UserSerializer, EventSerializer
from ..users.models import User
from ..events.models import Event as EventModel
from allauth.account.utils import send_email_confirmation
from texaslan.site_settings.models import SiteSettingService

class AuthRegisterUser(APIView):
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            new_user = serializer.save()
            send_email_confirmation(request._request, new_user)
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST)

class Status(APIView):

    def get(self, request, format=None):
        return Response({ 'rush': SiteSettingService.is_rush_open()})

class Event(APIView):
    serializer_class = EventSerializer

    def _extract_user_id_from_middleware(self, request):
        request.data['creator'] = request.user.get('id')

    def post(self, request, format=None):
        self._extract_user_id_from_middleware(request)
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, format=None):
        events = [self.serializer_class(event).data for event in EventModel.objects.all().order_by('-start_time')]
        return Response(events,
                status=status.HTTP_200_OK)

texaslan/applications/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView
from django.views.generic import FormView, UpdateView, ListView, TemplateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ApplicationForm, ReviewForm
from .models import Application, Review
from texaslan.utils.utils import OpenRushieRequiredMixin, ActiveRequiredMixin
from texaslan.users.models import User
from texaslan.events.models import Event


class ApplicationModifyView(OpenRushieRequiredMixin, UpdateView):
    template_name = 'applications/applications_form.html'
    form_class = ApplicationForm

    def get_object(self, queryset=None):
        (application, created) = Application.objects.get_or_create(applicant_user__pk=self.request.user.id)
        application.applicant_user = self.request.user
        return application

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, form.errors.as_data()['__all__'][0].message)
        return super(ApplicationModifyView, self).form_invalid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully saved application!')
        return reverse('applications:modify')


class ApplicationListView(ActiveRequiredMixin, TemplateView):
    template_name = 'applications/applications_list.html'

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)

        application_list = Application.objects.all()
        review_list = []
        avg_rating_list = []
        board_avg_rating_list = []
        anon_avg_rating_list = []
        rating_count_list = []
        events_attended_list = []
        for application in application_list:
            reviews = Review.objects.filter(application__pk=application.pk)
            avg_rating_total = 0
            avg_rating_count = 0
            board_avg_rating_total = 0
            board_avg_rating_count = 0
            events_attended_count = 0
            rating_count_list.append(len(reviews))

            for review in reviews:
                if review.rating is None or review.reviewer_user is None:
                    continue

                avg_rating_count += 1
                avg_rating_total += review.rating

                if review.reviewer_user.is_board():
                    board_avg_rating_count += 1
                    board_avg_rating_total += review.rating

            if avg_rating_count != 0:
                avg_rating_list.append("{0:.2f}".format(avg_rating_total / avg_rating_count))
            else:
                avg_rating_list.append("-")

            if board_avg_rating_count != 0:
                board_avg_rating_list.append("{0:.2f}".format(board_avg_rating_total / board_avg_rating_count))
            else:
                board_avg_rating_list.append("-")

            events_attended_list.append("0")

            try:
                Review.objects.get(application__pk=application.pk, reviewer_user__pk=self.request.user.pk)
                review_list.append(True)
            except Review.DoesNotExist:
                review_list.append(False)

        context['application_list'] = zip(application_list, review_list, avg_rating_list, board_avg_rating_list, rating_count_list, events_attended_list)
        return context


class ApplicationDetailView(ActiveRequiredMixin, FormView):
    template_name = 'applications/applications_detail.html'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetailView, self).get_context_data(**kwargs)
        app_id = int(self.kwargs.get("id"))
        context['application'] = get_object_or_404(Application, pk=app_id)
        context['rushie'] = context['application'].applicant_user

        reviews = Review.objects.filter(application__pk=app_id)
        member_avg_rating_total = 0
        member_avg_rating_count = 0
        board_avg_rating_total = 0
        board_avg_rating_count = 0
        anon_avg_rating_total = 0
        anon_avg_rating_count = 0
        events_attended_count = 0

        for review in reviews:
            if review.rating is None:
                continue

            if review.reviewer_user is None:
                anon_avg_rating_count += 1
                anon_avg_rating_total += review.rating
            elif review.reviewer_user.is_board():
                board_avg_rating_count += 1
                board_avg_rating_total += review.rating
            else:
                member_avg_rating_count += 1
                member_avg_rating_total += review.rating

        avg_rating_total = member_avg_rating_total + board_avg_rating_total
        avg_rating_count = member_avg_rating_count + board_avg_rating_count

        if avg_rating_count != 0:
            context['avg_rating'] = "{0:.2f}".format(avg_rating_total / avg_rating_count)
        else:
            context['avg_rating'] = "-"

        if member_avg_rating_count != 0:
            context['member_avg_rating'] = "{0:.2f}".format(member_avg_rating_total / member_avg_rating_count)
        else:
            context['member_avg_rating'] = "-"

        if board_avg_rating_count != 0:
            context['board_avg_rating'] = "{0:.2f}".format(board_avg_rating_total / board_avg_rating_count)
        else:
            context['board_avg_rating'] = "-"

        if anon_avg_rating_count != 0:
            context['anon_avg_rating'] = "{0:.2f}".format(anon_avg_rating_total / anon_avg_rating_count)
        else:
            context['anon_avg_rating'] = "-"

        context['events_attended'] = events_attended_count

        context['reviews'] = reviews
        context['events'] = list(context['rushie'].event_attendees.all())
        print(context['events'])
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.modify_review()
        return super(ApplicationDetailView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('applications:list')

texaslan/comments/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView

from .forms import CommentForm
from .models import Comment
from texaslan.utils.utils import ActiveRequiredMixin


class CommentView(ActiveRequiredMixin, FormView):
    template_name = 'comments/comments_list.html'
    form_class = CommentForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
        return context

    def form_valid(self, form):
        form.create_comment()
        return super(CommentView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully created the comment!')
        return reverse('comments:list')

texaslan/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Lambda Alpha Nu{% endblock title %}</title>
    <meta name="description"
          content="The co-ed technology fraternity.">
    <meta name="theme-color" content="#2196f3">

    <!-- SEO -->
    <meta property="og:title" content="LAN">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.texaslan.org">
    <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}
{% block open_graph_image %}{% static 'images/lan-crest.png' %}{% endblock open_graph_image %}"/>
    <meta property="og:site_name" content="texaslan.org">
    <meta property="og:description"
          content="The co-ed social computing fraternity.">
    <meta name="keywords" content="fraternity, computer science, computer, LAN, texas, UT, austin">
    <link rel="canonical" href="https://www.texaslan.org/">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/icons/favicon-192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/icons/favicon-32.png' %}"/>
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/icons/favicon-96.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/icons/favicon-16.png' %}"/>

    <link rel="apple-touch-icon" sizes="160x160" href="{% static 'images/icons/apple-touch-icon@3x.png' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon-96x96.png' %}">
    <link rel='mask-icon' href='{% static 'images/icons/mask.svg' %}' color='#2196f3'>

    {% block css %}
        <link href="{% static 'generated_css/base.min.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body>

<div class="m-b">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed"
                        type="button"
                        data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:feed' %}">
                    <p>ΛΑΝ</p>
                </a>
            </div>
            <div class="collapse navbar-collapse"
                 id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% if request.user.is_open_rushie %}
                        <li class="{% block applications_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'applications:modify' %}">Application</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_active_user %}
                        <li class="{% block applications_list_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'applications:list' %}">Applications</a>
                        </li>
                        <li class="{% block comments_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'comments:list' %}">Comments</a>
                        </li>
                        <!-- Changed from: if voting_open due to no voting tab in officer elections. -->
                        {% if not is_voting_closed %}
                            <li class="{% block voting_tab %}{% endblock %} nav-item">
                                <a class="nav-link" href="{% url 'voting:list' %}">Voting</a>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% if request.user.is_active_user or request.user.is_alumni %}
                        <li class="{% block members_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'users:list' %}">Members</a>
                        </li>
                        <li class="{% block photos_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{{ photos_url }}">Photos</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="{% block notifications_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'notifications:list' %}">Notifications</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_officer %}
                        <li class="{% block notify_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'notify:notify' %}">Notify</a>
                        </li>
                        <li class="{% block go_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'go:list' %}">Go</a>
                        </li>
                        <li class="{% block gsuite_tab %}{% endblock %} nav-item">
                            <a class="dropdown-toggle"
                                   data-toggle="dropdown"
                                   aria-expanded="false"
                                   role="button"
                                   href="#">
                                    GSuite <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu"
                                role="menu">
                                <li>
                                    <a href="http://drive.lambdaalphanu.org" target="_blank">{% trans "Drive" %}</a>
                                </li>
                                <li>
                                    <a href="http://cal.lambdaalphanu.org" target="_blank">{% trans "Calendar" %}</a>
                                </li>
                                <li>
                                    <a href="http://mail.lambdaalphanu.org" target="_blank">{% trans "Mail" %}</a>
                                </li>
                                <li>
                                    <a href="https://groups.google.com/a/texaslan.org" target="_blank">{% trans "Groups" %}</a>
                                </li>
                            </ul>
                        </li>
                        <li class="{% block admin_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li>
                            <a class="dropdown-toggle"
                               data-toggle="dropdown"
                               aria-expanded="false"
                               role="button"
                               href="#">
                                {{ user.get_username }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu"
                                role="menu">
                                <li>
                                    <a href="{% url 'users:detail' request.user.username %}">{% trans "Profile" %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'users:update' %}">{% trans "Settings" %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a id="log-in-link" href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="alert-container text-center">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissable {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
        {% endfor %}
    {% endif %}

</div> <!-- /container -->

{% block content %}
    <p>Use this document as a way to quick start any new project.</p>
{% endblock content %}


<footer>
    <div class="container">
        <div class="text">
            <ul class="social">
                <li><a href="mailto:general@texaslan.org" data-toggle="tooltip" title="Email"><i
                        class="fa fa-envelope-o"></i></a></li>
                <li><a href="https://facebook.com/texaslambdaalphanu/" data-toggle="tooltip" title="Facebook"><i
                        class="fa fa-facebook"></i></a></li>
                <li><a href="https://github.com/TexasLAN" data-toggle="tooltip" title="Github"><i
                        class="fa fa-github"></i></a></li>
            </ul>
            <p class="copyright"> © 2019 Texas Lambda Alpha Nu
            </p>
        </div>
    </div>
</footer>

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script defer src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Google Analytics -->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-48035110-3', 'auto');
        ga('send', 'pageview');
    </script>

    <!-- Latest JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Tether - a requirement for Bootstrap tooltips -->
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script async src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script async src="{% static 'generated_js/project.min.js' %}"></script>
    {% block extra-js %}{% endblock %}
{% endblock javascript %}

</body>
</html>