config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                #   url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                #   url(r'^rush/$', TemplateView.as_view(template_name='pages/rush.html'), name='rush'),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include('texaslan.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('texaslan.events.urls', namespace='events')),
                  url(r'^', include('texaslan.home.urls', namespace='home')),
                  url(r'^go/', include('texaslan.go.urls', namespace='go')),
                  url(r'^notify/', include('texaslan.notify.urls', namespace='notify')),
                  url(r'^comments/', include('texaslan.comments.urls', namespace='comments')),
                  url(r'^applications/', include('texaslan.applications.urls', namespace='applications')),
                  url(r'^voting/', include('texaslan.voting.urls', namespace='voting')),
                  url(r'^notifications/', include('texaslan.notifications.urls', namespace='notifications')),
                  url(r'^slack/', include('django_slack_oauth.urls')),
                  url(r'^api/v1/', include('texaslan.api.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

texaslan/api/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from .views import AuthRegisterUser, Status, Event
from ..users.models import User
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    url(r'^jwt/login/', obtain_jwt_token),
    url(r'^jwt/refresh/', refresh_jwt_token),
    url(r'^jwt/verify/', verify_jwt_token),
    url(r'^jwt/register/', AuthRegisterUser.as_view()),
    url(r'^status/rush/', Status.as_view()),
    url(r'^events/', Event.as_view()),
]

texaslan/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

texaslan/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

texaslan/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^~update/slack-delete/$',
        view=views.delete_slack_token,
        name='slack-delete'
    ),
]

texaslan/home/models.py
from django.db import models

# Create your models here.

texaslan/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

import hashlib

from django.contrib.auth.models import Group, AbstractUser, BaseUserManager
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

GENDER_CHOICES = (
    ("M", "Male"),
    ("F", "Female"),
    ("N", "Non - binary"),
    ("P", "Prefer not to answer")
)
CONCENTRATION_CHOICES = (
    ("CS", "Computer Science"),
    ("D", "Design"),
    ("B", "Business"),
    ("EE", "Electrical Engineering"),
    ("M", "Math"),
    ("MIS", "Management Information Systems"),
    ("O", "Other")
)
LAN_CLASS = (
    ("F", "Founder"),
    ("A", "Alpha"),
    ("B", "Beta"),
    ("G", "Gamma"),
    ("D", "Delta"),
    ("E", "Epsilon"),
    ("Z", "Zeta"),
    ("Et", "Eta"),
    ("T", "Theta"),
)

SEMESTERS = (
    ("F14", "Fall 2014"),
    ("S15", "Spring 2015"),
    ("F15", "Fall 2015"),
    ("S16", "Spring 2016"),
    ("F16", "Fall 2016"),
    ("S17", "Spring 2017"),
    ("F17", "Fall 2017"),
    ("S18", "Spring 2018"),
    ("F18", "Fall 2018"),
    ("S19", "Spring 2019"),
    ("F19", "Fall 2019"),
)

class ActiveSemester(models.Model):
    semester = models.CharField(max_length=255)

    def __str__(self):
        return self.semester

    class Meta:
        db_table = "semester"

class UserManager(BaseUserManager):

    def get_by_natural_key(self, key):
        return self.get(**{'email': key})

    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have a valid e-mail address')

        user = self.model(
                email=self.normalize_email(email),
                username=self.normalize_email(email),
                full_name=kwargs.get('full_name'),
                graduation_date=kwargs.get('graduation_date'),
                concentration=kwargs.get('concentration'),
            )
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password=None, **kwargs):
        user = self.create_user(email, password, kwargs)
        user.is_admin = True
        user.save()

        return user


@python_2_unicode_compatible
class User(AbstractUser):
    full_name = models.CharField(max_length=255)
    nick_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    graduation_date = models.DateField()
    concentration = models.CharField(max_length=3, choices=CONCENTRATION_CHOICES, default="O")
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default="P")
    lan_class = models.CharField(max_length=3, choices=LAN_CLASS, null=True, blank=True)
    active_semesters = models.ManyToManyField(ActiveSemester, blank=True)
    events_attended = models.CharField(max_length=2, default="0")
    USERNAME_FIELD = 'username'
    REQUIRED_FIELD = 'email'

    def get_username(self):
        return self.email


    objects = UserManager()

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_gravatar_image_url(self):
        return 'https://secure.gravatar.com/avatar/' + hashlib.md5(
            self.email.lower().encode('utf-8')).hexdigest() + '?s=200'

    def get_gender(self):
        for (short, actual) in GENDER_CHOICES:
            if short == self.gender:
                return actual
        return "N/A"

    def get_concentration(self):
        for (short, actual) in CONCENTRATION_CHOICES:
            if short == self.concentration:
                return actual
        return "N/A"

    # User Type

    def is_disabled(self):
        return not self.is_active

    def is_open_rushie(self):
        return self.groups.filter(name="Open Rushie").exists()

    def is_closed_rushie(self):
        return self.groups.filter(name="Closed Rushie").exists()

    def is_rushie(self):
        return self.is_open_rushie() or self.is_closed_rushie()

    def is_pledge(self):
        return self.groups.filter(name="Pledge").exists()

    def is_active_user(self):
        return self.groups.filter(name="Active").exists()

    def is_officer(self):
        return self.groups.filter(name="Officer").exists()

    def is_board(self):
        return self.groups.filter(name="Board").exists()

    def is_inactive(self):
        return self.groups.filter(name="Inactive").exists()

    def is_alumni(self):
        return self.groups.filter(name="Alumni").exists()


class UserService:
    # User Getters

    @staticmethod
    def get_disabled_users():
        return [user for user in User.objects.all() if user.is_disabled()]

    @staticmethod
    def get_open_rushie_users():
        return [user for user in User.objects.all() if user.is_open_rushie()]

    @staticmethod
    def get_closed_rushie_users():
        return [user for user in User.objects.all() if user.is_closed_rushie()]

    @staticmethod
    def get_pledge_users():
        return [user for user in User.objects.all() if user.is_pledge()]

    @staticmethod
    def get_active_users():
        return [user for user in User.objects.all() if user.is_active_user()]

    @staticmethod
    def get_officer_users():
        return [user for user in User.objects.all() if user.is_officer()]

    @staticmethod
    def get_board_users():
        return [user for user in User.objects.all() if user.is_board()]

    @staticmethod
    def get_inactive_users():
        return [user for user in User.objects.all() if user.is_inactive()]

    @staticmethod
    def get_alumni_users():
        return [user for user in User.objects.all() if user.is_alumni()]

    # Email Getters

    @staticmethod
    def get_disabled_users_emails():
        return [user.email for user in UserService.get_disabled_users()]

    @staticmethod
    def get_open_rushie_users_emails():
        return [user.email for user in UserService.get_open_rushie_users()]

    @staticmethod
    def get_closed_rushie_users_emails():
        return [user.email for user in UserService.get_closed_rushie_users()]

    @staticmethod
    def get_pledge_users_emails():
        return [user.email for user in UserService.get_pledge_users()]

    @staticmethod
    def get_active_users_emails():
        return [user.email for user in UserService.get_active_users()]

    @staticmethod
    def get_officer_users_emails():
        return [user.email for user in UserService.get_officer_users()]

    @staticmethod
    def get_board_users_emails():
        return [user.email for user in UserService.get_board_users()]

    @staticmethod
    def get_inactive_users_emails():
        return [user.email for user in UserService.get_inactive_users()]

    @staticmethod
    def get_alumni_users_emails():
        return [user.email for user in UserService.get_alumni_users()]

texaslan/api/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from .serializers import UserSerializer, EventSerializer
from ..users.models import User
from ..events.models import Event as EventModel
from allauth.account.utils import send_email_confirmation
from texaslan.site_settings.models import SiteSettingService

class AuthRegisterUser(APIView):
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            new_user = serializer.save()
            send_email_confirmation(request._request, new_user)
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST)

class Status(APIView):

    def get(self, request, format=None):
        return Response({ 'rush': SiteSettingService.is_rush_open()})

class Event(APIView):
    serializer_class = EventSerializer

    def _extract_user_id_from_middleware(self, request):
        request.data['creator'] = request.user.get('id')

    def post(self, request, format=None):
        self._extract_user_id_from_middleware(request)
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, format=None):
        events = [self.serializer_class(event).data for event in EventModel.objects.all().order_by('-start_time')]
        return Response(events,
                status=status.HTTP_200_OK)

texaslan/comments/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView

from .forms import CommentForm
from .models import Comment
from texaslan.utils.utils import ActiveRequiredMixin


class CommentView(ActiveRequiredMixin, FormView):
    template_name = 'comments/comments_list.html'
    form_class = CommentForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
        return context

    def form_valid(self, form):
        form.create_comment()
        return super(CommentView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully created the comment!')
        return reverse('comments:list')

texaslan/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView

from texaslan.utils.utils import OfficerRequiredMixin, EventPermissionsRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        qs = qs.filter(start_time__gte=now)

        tags = EventTag.objects.all()
        open_tag = [tag.id for tag in tags.filter(name="Open Rush")]
        closed_tag = [tag.id for tag in tags.filter(name="Closed Rush")]

        if self.request.user.is_anonymous() or self.request.user.is_open_rushie():
            qs = qs.filter(event_tags__in=open_tag)
        elif self.request.user.is_closed_rushie():
            qs = qs.filter(event_tags__in=closed_tag)

        return qs


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(start_time__year=year, start_time__month=month)

    if request.user.is_anonymous() or request.user.is_open_rushie():
        event_list = [event for event in event_list if event.is_open_rush_safe()]
    elif request.user.is_closed_rushie():
        event_list = [event for event in event_list if event.is_closed_rush_safe()]
    else:
        event_list = [event for event in event_list if event.is_member_and_pledge_safe()]

    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(EventPermissionsRequiredMixin, DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(OfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')

texaslan/templates/users/base.html
{% extends "base.html" %}
{% block members_tab %}active{% endblock %}

texaslan/templates/users/user_detail.html
{% extends "users/base.html" %}
{% load static %}

{% block title %}LAN - {{ object.username }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <h1>{{ object.full_name }}</h1>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">Member Information</h1>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-3 thumbnail">
                            <img class="circle-img" src="{{ object.get_gravatar_image_url }}"/>
                            {% if object == request.user %}
                                <div class="caption">
                                    <p>
                                        <a href="https://en.gravatar.com/emails/"
                                           class="match_parent_width btn btn-primary"
                                           role="button">
                                            Change on Gravatar
                                        </a>
                                    </p>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-md-9">
                            {% if object.get_lan_class_display is None %}
                            <h5>Nickname: </h5>
                            <p>{{ object.nick_name }}</p>
                            <h5>Graduation Date: </h5>
                            <p>{{ object.graduation_date }}</p>
                            {% else %}
                            {% if slack_auth is None %}
                                <div class="alert alert-info" role="alert">
                                    <a href="{% url 'slack_auth' %}">Connect your Slack account</a> to automatically clear old files.
                                </div>
                            {% endif %}
                            <h5>Nickname: </h5>
                            <p>{{ object.nick_name }}</p>
                            <h5>Pledge Class:</h5>
                            <p>{{ object.get_lan_class_display }}</p>
                            <h5>Graduation Date: </h5>
                            <p>{{ object.graduation_date }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

texaslan/templates/users/user_form.html
{% extends "users/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <link href="{% static 'generated_css/datepicker_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-material-datetimepicker.js' %}"></script>
    <script>
        $('#id_graduation_date').bootstrapMaterialDatePicker({weekStart: 0, time: false, format: "YYYY-MM-DD"});
    </script>
{% endblock %}

{% block title %}LAN - {{ user.username }}{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ user.username }}</h1>
        <a class="btn btn-primary" href="{% url 'account_email' %}">Update E-Mail</a>
        <a class="btn btn-primary" href="{% url 'account_change_password' %}">Change Password</a>
        <form class="form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'users:update' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </div>
        </form>
    </div>

    <div class="container">
        <h3>Slack</h3>
        {% if slack_auth is None %}
            <p>Connect your Slack account to automatically manage files.</p>
            <a class="btn btn-primary" href="{% url 'slack_auth' %}">Connect Slack Account</a><br><br>
        {% else %}
            <p>Slack account connected. <a href="slack-delete">Disconnect</a></p>
            <p>Files older than 30 days are automatically deleted.</p>
        {% endif %}
    </div>
{% endblock %}