config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                #   url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                #   url(r'^rush/$', TemplateView.as_view(template_name='pages/rush.html'), name='rush'),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include('texaslan.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('texaslan.events.urls', namespace='events')),
                  url(r'^', include('texaslan.home.urls', namespace='home')),
                  url(r'^go/', include('texaslan.go.urls', namespace='go')),
                  url(r'^notify/', include('texaslan.notify.urls', namespace='notify')),
                  url(r'^comments/', include('texaslan.comments.urls', namespace='comments')),
                  url(r'^applications/', include('texaslan.applications.urls', namespace='applications')),
                  url(r'^voting/', include('texaslan.voting.urls', namespace='voting')),
                  url(r'^notifications/', include('texaslan.notifications.urls', namespace='notifications')),
                  url(r'^slack/', include('django_slack_oauth.urls')),
                  url(r'^api/v1/', include('texaslan.api.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

texaslan/api/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from .views import AuthRegisterUser, Status, Event
from ..users.models import User
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    url(r'^jwt/login/', obtain_jwt_token),
    url(r'^jwt/refresh/', refresh_jwt_token),
    url(r'^jwt/verify/', verify_jwt_token),
    url(r'^jwt/register/', AuthRegisterUser.as_view()),
    url(r'^status/rush/', Status.as_view()),
    url(r'^events/', Event.as_view()),
]

texaslan/events/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Events
    url(
        regex=r'^$',
        view=views.EventListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^calendar/$',
        view=views.calendar,
        name='calendar'
    ),
    url(
        regex=r'^calendar/(?P<year>\d+)/(?P<month>\d+)/$',
        view=views.calendar,
        name='calendar'
    ),
    url(
        regex=r'^(?P<id>[\w.@+-]+)/$',
        view=views.EventDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^confirm/(?P<id>[\w.@+-]+)/(?P<username>[\w.@+-]+)/$',
        view=views.EventConfirmAttendanceView.as_view(),
        name='confirm'
    ),
]

texaslan/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

texaslan/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

texaslan/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),

    url(
        regex=r'^~update/slack-delete/$',
        view=views.delete_slack_token,
        name='slack-delete'
    ),
]

texaslan/home/models.py
from django.db import models

# Create your models here.

texaslan/notify/models.py
from django.db import models

# Create your models here.

texaslan/applications/forms.py
from django import forms
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404

from .models import Application, Review
from texaslan.users.models import User
from texaslan.site_settings.models import SiteSettingService


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['question_1', 'question_2', 'question_3', 'question_4', 'question_5', 'question_6', 'question_7']

    def clean(self):
        application = self.save(commit=False)
        # This will validate if forms can be submitted or not

        if application.is_submitted:
            raise forms.ValidationError("Applications was already submitted")

        if not SiteSettingService.is_rush_open():
            raise forms.ValidationError("Application is late")

        if 'submit_btn' in self.data:
            application.is_submitted = True

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            application = self.save(commit=False)
            if application.is_submitted:
                for key, _ in self.fields.items():
                    self.fields[key].widget.attrs['readonly'] = True


RATING_CHOICES = (
    (1, "Strong No"),
    (2, "Weak No"),
    (3, "Neutral"),
    (4, "Weak Yes"),
    (5, "Strong Yes"),
)


class ReviewForm(forms.ModelForm):
    is_anon_comment = forms.BooleanField(label="Is anonymous comment?", required=False)

    class Meta:
        model = Review
        fields = ['comment', 'rating']

    def modify_review(self):
        print(self.data)
        if "is_anon_comment" not in self.data or self.data["is_anon_comment"] == 'off':
            application_id = int(self.data['application_id'])
            username = self.data['review_username']
            comment = self.cleaned_data['comment']
            rating = self.cleaned_data['rating']

            application = get_object_or_404(Application, pk=application_id)
            reviewer = get_object_or_404(User, username=username)
            try:
                review = Review.objects.get(application__pk=application_id, reviewer_user__pk=reviewer.pk)
            except Review.DoesNotExist:
                review = Review.objects.create()
            review.rating = rating
            review.comment = comment
            review.application = application
            review.reviewer_user = reviewer
            review.save()
        else:
            anon_review = Review.objects.create()
            anon_review.rating = self.cleaned_data['rating']
            anon_review.comment = self.cleaned_data['comment']
            anon_review.application = get_object_or_404(Application, pk=int(self.data['application_id']))
            anon_review.save()
        pass

texaslan/api/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from .serializers import UserSerializer, EventSerializer
from ..users.models import User
from ..events.models import Event as EventModel
from allauth.account.utils import send_email_confirmation
from texaslan.site_settings.models import SiteSettingService

class AuthRegisterUser(APIView):
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            new_user = serializer.save()
            send_email_confirmation(request._request, new_user)
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST)

class Status(APIView):

    def get(self, request, format=None):
        return Response({ 'rush': SiteSettingService.is_rush_open()})

class Event(APIView):
    serializer_class = EventSerializer

    def _extract_user_id_from_middleware(self, request):
        request.data['creator'] = request.user.get('id')

    def post(self, request, format=None):
        self._extract_user_id_from_middleware(request)
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, format=None):
        events = [self.serializer_class(event).data for event in EventModel.objects.all().order_by('-start_time')]
        return Response(events,
                status=status.HTTP_200_OK)

texaslan/applications/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView
from django.views.generic import FormView, UpdateView, ListView, TemplateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ApplicationForm, ReviewForm
from .models import Application, Review
from texaslan.utils.utils import OpenRushieRequiredMixin, ActiveRequiredMixin
from texaslan.users.models import User
from texaslan.events.models import Event


class ApplicationModifyView(OpenRushieRequiredMixin, UpdateView):
    template_name = 'applications/applications_form.html'
    form_class = ApplicationForm

    def get_object(self, queryset=None):
        (application, created) = Application.objects.get_or_create(applicant_user__pk=self.request.user.id)
        application.applicant_user = self.request.user
        return application

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, form.errors.as_data()['__all__'][0].message)
        return super(ApplicationModifyView, self).form_invalid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully saved application!')
        return reverse('applications:modify')


class ApplicationListView(ActiveRequiredMixin, TemplateView):
    template_name = 'applications/applications_list.html'

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)

        application_list = Application.objects.all()
        review_list = []
        avg_rating_list = []
        board_avg_rating_list = []
        anon_avg_rating_list = []
        rating_count_list = []
        events_attended_list = []
        for application in application_list:
            reviews = Review.objects.filter(application__pk=application.pk)
            avg_rating_total = 0
            avg_rating_count = 0
            board_avg_rating_total = 0
            board_avg_rating_count = 0
            events_attended_count = 0
            rating_count_list.append(len(reviews))

            for review in reviews:
                if review.rating is None or review.reviewer_user is None:
                    continue

                avg_rating_count += 1
                avg_rating_total += review.rating

                if review.reviewer_user.is_board():
                    board_avg_rating_count += 1
                    board_avg_rating_total += review.rating

            if avg_rating_count != 0:
                avg_rating_list.append("{0:.2f}".format(avg_rating_total / avg_rating_count))
            else:
                avg_rating_list.append("-")

            if board_avg_rating_count != 0:
                board_avg_rating_list.append("{0:.2f}".format(board_avg_rating_total / board_avg_rating_count))
            else:
                board_avg_rating_list.append("-")

            events_attended_list.append("0")

            try:
                Review.objects.get(application__pk=application.pk, reviewer_user__pk=self.request.user.pk)
                review_list.append(True)
            except Review.DoesNotExist:
                review_list.append(False)

        context['application_list'] = zip(application_list, review_list, avg_rating_list, board_avg_rating_list, rating_count_list, events_attended_list)
        return context


class ApplicationDetailView(ActiveRequiredMixin, FormView):
    template_name = 'applications/applications_detail.html'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetailView, self).get_context_data(**kwargs)
        app_id = int(self.kwargs.get("id"))
        context['application'] = get_object_or_404(Application, pk=app_id)
        context['rushie'] = context['application'].applicant_user

        reviews = Review.objects.filter(application__pk=app_id)
        member_avg_rating_total = 0
        member_avg_rating_count = 0
        board_avg_rating_total = 0
        board_avg_rating_count = 0
        anon_avg_rating_total = 0
        anon_avg_rating_count = 0
        events_attended_count = 0

        for review in reviews:
            if review.rating is None:
                continue

            if review.reviewer_user is None:
                anon_avg_rating_count += 1
                anon_avg_rating_total += review.rating
            elif review.reviewer_user.is_board():
                board_avg_rating_count += 1
                board_avg_rating_total += review.rating
            else:
                member_avg_rating_count += 1
                member_avg_rating_total += review.rating

        avg_rating_total = member_avg_rating_total + board_avg_rating_total
        avg_rating_count = member_avg_rating_count + board_avg_rating_count

        if avg_rating_count != 0:
            context['avg_rating'] = "{0:.2f}".format(avg_rating_total / avg_rating_count)
        else:
            context['avg_rating'] = "-"

        if member_avg_rating_count != 0:
            context['member_avg_rating'] = "{0:.2f}".format(member_avg_rating_total / member_avg_rating_count)
        else:
            context['member_avg_rating'] = "-"

        if board_avg_rating_count != 0:
            context['board_avg_rating'] = "{0:.2f}".format(board_avg_rating_total / board_avg_rating_count)
        else:
            context['board_avg_rating'] = "-"

        if anon_avg_rating_count != 0:
            context['anon_avg_rating'] = "{0:.2f}".format(anon_avg_rating_total / anon_avg_rating_count)
        else:
            context['anon_avg_rating'] = "-"

        context['events_attended'] = events_attended_count

        context['reviews'] = reviews
        context['events'] = list(context['rushie'].event_attendees.all())
        print(context['events'])
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.modify_review()
        return super(ApplicationDetailView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('applications:list')

texaslan/comments/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView

from .forms import CommentForm
from .models import Comment
from texaslan.utils.utils import ActiveRequiredMixin


class CommentView(ActiveRequiredMixin, FormView):
    template_name = 'comments/comments_list.html'
    form_class = CommentForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
        return context

    def form_valid(self, form):
        form.create_comment()
        return super(CommentView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully created the comment!')
        return reverse('comments:list')

texaslan/templates/events/event_calendar.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}LAN - Calendar{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/events_calendar.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="container">
    <div class="clndr">
        <div class="calendar-wrap">
            {{ calendar }}
        </div>
    </div>
    </div>
{% endblock content %}

texaslan/templates/events/event_confirm_attendance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}LAN - {{ event.title }} & {{ user.username }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">Confirm attendance for {{ user.full_name }}</h1>
            </div>
            <div class="panel-body">
                <div class="text-center">
                    <img class="circle-img" src="{{ user.get_gravatar_image_url }}"/>
                </div>
                <form class="form-horizontal" method="post" action="{% url 'events:confirm' event.id user.username %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="event_id" value="{{ event.id }}"/>
                    <input type="hidden" name="username" value="{{ user.username }}"/>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

texaslan/templates/events/event_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'generated_css/addtocal_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/atc.min.js' %}"></script>
    <script src="{% static 'js/jquery.qrcode.js' %}"></script>
    <script src="{% static 'js/qrcode.js' %}"></script>
    {% if request.user.is_authenticated %}
        <script>
            jQuery('#qrcode').qrcode({
                text: "{{ request.get_host }}{% url 'events:confirm' object.id request.user.username %}"
            });
        </script>
    {% endif %}
{% endblock %}

{% block title %}LAN - {{ object.title }}{% endblock %}

{% block content %}
    <div class="container">
        {% if request.user.is_authenticated and not request.user in object.attendees.all %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">Sign in to event</h1>
                </div>
                <div class="panel-body">
                    <p>Get an officer to sign you in at the event</p>
                    <div id="qrcode" class="text-center"></div>
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">{{ object.title }}</h1>
            </div>
            <div class="panel-body">
                <h5>Location: </h5>
                <p>{{ object.location }}</p>
                <h5>Starts: </h5>
                <p>{{ object.start_time }}</p>
                <h5>Ends: </h5>
                <p>{{ object.end_time }}</p>
                <span class="addtocalendar atc-style-blue">
                    <var class="atc_event">
                        <var class="atc_date_start">{{ object.start_time }}</var>
                        <var class="atc_date_end">{{ object.end_time }}</var>
                        <var class="atc_timezone">America/Chicago</var>
                        <var class="atc_title">{{ object.title }}</var>
                        <var class="atc_description">{{ object.description }}</var>
                        <var class="atc_location">{{ object.location }}</var>
                        <var class="atc_organizer">{{ object.creator.full_name }}</var>
                        <var class="atc_organizer_email">{{ object.creator.email }}</var>
                    </var>
                </span>
                <h5>Creator: </h5>
                <p>{{ object.creator.full_name }}</p>
                {% if not object.is_gm_or_om or request.user.is_active %}
                    <h5>Description: </h5>
                    <p>{{ object.description }}</p>
                {% endif %}
                <h5>Attendees: </h5>
                <p>{{ object.attendees.all|length }}</p>
                {% if request.user.is_staff %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                        </tr>
                        {% for attendee in object.attendees.all %}
                            <tr>
                                <td>{{ attendee.full_name }}</td>
                                <td>{{ attendee.email }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

texaslan/templates/events/event_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}LAN - Events{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/sortable_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/bootstrap-sortable.min.js' %}"></script>
{% endblock %}

{% block content %}
    {% if event_list %}
        <div class="events">
            {% for event in event_list %}
                <div class="panel card container">
                    <div class="row">
                        <div class="card-content col-md-8 col-xs-7">
                            <h1 class="card-title">{{ event.title }}</h1>
                            <p>{{ event.location }}</p>
                            <p>{{ event.start_time }}</p>
                        </div>
                        <div class="card-media col-md-4 col-xs-1">
                            <img src="{{ event.image_url }}"/>
                        </div>
                    </div>
                    <div class="card-actions row">
                        <a class="btn btn-flat" href="{% url 'events:detail' event.id %}">View</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3 align="center">No upcoming events</h3>
    {% endif %}
{% endblock content %}