config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                #   url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                #   url(r'^rush/$', TemplateView.as_view(template_name='pages/rush.html'), name='rush'),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include('texaslan.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('texaslan.events.urls', namespace='events')),
                  url(r'^', include('texaslan.home.urls', namespace='home')),
                  url(r'^go/', include('texaslan.go.urls', namespace='go')),
                  url(r'^notify/', include('texaslan.notify.urls', namespace='notify')),
                  url(r'^comments/', include('texaslan.comments.urls', namespace='comments')),
                  url(r'^applications/', include('texaslan.applications.urls', namespace='applications')),
                  url(r'^voting/', include('texaslan.voting.urls', namespace='voting')),
                  url(r'^notifications/', include('texaslan.notifications.urls', namespace='notifications')),
                  url(r'^slack/', include('django_slack_oauth.urls')),
                  url(r'^api/v1/', include('texaslan.api.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar

    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

texaslan/api/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls import url
from .views import AuthRegisterUser, Status, Event
from ..users.models import User
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    url(r'^jwt/login/', obtain_jwt_token),
    url(r'^jwt/refresh/', refresh_jwt_token),
    url(r'^jwt/verify/', verify_jwt_token),
    url(r'^jwt/register/', AuthRegisterUser.as_view()),
    url(r'^status/rush/', Status.as_view()),
    url(r'^events/', Event.as_view()),
]

texaslan/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

texaslan/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

texaslan/voting/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.CandidateListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^apply/(?P<position>[a-zA-Z0-9_-]+)/$',
        view=views.CandidateApplyView.as_view(),
        name='apply'
    ),
    url(
        regex=r'^candidate/(?P<position>[a-zA-Z0-9_-]+)/(?P<username>[\w.@+-]+)/$',
        view=views.CandidateDetailsView.as_view(),
        name='candidate_detail'
    ),
    url(
        regex=r'^vote/$',
        view=views.VoteView.as_view(),
        name='vote'
    ),
]

texaslan/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.Form):

    message = forms.CharField(widget=forms.Textarea)

    def create_comment(self):
        new_comment = Comment()
        new_comment.message = self.cleaned_data['message']
        new_comment.is_open = True
        new_comment.save()
        pass

texaslan/events/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Event
from ..users.models import User


class ConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        event_id = int(self.data['event_id'])
        username = self.data['username']

        event = get_object_or_404(Event, pk=event_id)
        user = get_object_or_404(User, username=username)
        event.attendees.add(user)
        pass

texaslan/api/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from .serializers import UserSerializer, EventSerializer
from ..users.models import User
from ..events.models import Event as EventModel
from allauth.account.utils import send_email_confirmation
from texaslan.site_settings.models import SiteSettingService

class AuthRegisterUser(APIView):
    serializer_class = UserSerializer
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            new_user = serializer.save()
            send_email_confirmation(request._request, new_user)
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST)

class Status(APIView):

    def get(self, request, format=None):
        return Response({ 'rush': SiteSettingService.is_rush_open()})

class Event(APIView):
    serializer_class = EventSerializer

    def _extract_user_id_from_middleware(self, request):
        request.data['creator'] = request.user.get('id')

    def post(self, request, format=None):
        self._extract_user_id_from_middleware(request)
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                    status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, format=None):
        events = [self.serializer_class(event).data for event in EventModel.objects.all().order_by('-start_time')]
        return Response(events,
                status=status.HTTP_200_OK)

texaslan/applications/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView
from django.views.generic import FormView, UpdateView, ListView, TemplateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ApplicationForm, ReviewForm
from .models import Application, Review
from texaslan.utils.utils import OpenRushieRequiredMixin, ActiveRequiredMixin
from texaslan.users.models import User
from texaslan.events.models import Event


class ApplicationModifyView(OpenRushieRequiredMixin, UpdateView):
    template_name = 'applications/applications_form.html'
    form_class = ApplicationForm

    def get_object(self, queryset=None):
        (application, created) = Application.objects.get_or_create(applicant_user__pk=self.request.user.id)
        application.applicant_user = self.request.user
        return application

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, form.errors.as_data()['__all__'][0].message)
        return super(ApplicationModifyView, self).form_invalid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully saved application!')
        return reverse('applications:modify')


class ApplicationListView(ActiveRequiredMixin, TemplateView):
    template_name = 'applications/applications_list.html'

    def get_context_data(self, **kwargs):
        context = super(ApplicationListView, self).get_context_data(**kwargs)

        application_list = Application.objects.all()
        review_list = []
        avg_rating_list = []
        board_avg_rating_list = []
        anon_avg_rating_list = []
        rating_count_list = []
        events_attended_list = []
        for application in application_list:
            reviews = Review.objects.filter(application__pk=application.pk)
            avg_rating_total = 0
            avg_rating_count = 0
            board_avg_rating_total = 0
            board_avg_rating_count = 0
            events_attended_count = 0
            rating_count_list.append(len(reviews))

            for review in reviews:
                if review.rating is None or review.reviewer_user is None:
                    continue

                avg_rating_count += 1
                avg_rating_total += review.rating

                if review.reviewer_user.is_board():
                    board_avg_rating_count += 1
                    board_avg_rating_total += review.rating

            if avg_rating_count != 0:
                avg_rating_list.append("{0:.2f}".format(avg_rating_total / avg_rating_count))
            else:
                avg_rating_list.append("-")

            if board_avg_rating_count != 0:
                board_avg_rating_list.append("{0:.2f}".format(board_avg_rating_total / board_avg_rating_count))
            else:
                board_avg_rating_list.append("-")

            events_attended_list.append("0")

            try:
                Review.objects.get(application__pk=application.pk, reviewer_user__pk=self.request.user.pk)
                review_list.append(True)
            except Review.DoesNotExist:
                review_list.append(False)

        context['application_list'] = zip(application_list, review_list, avg_rating_list, board_avg_rating_list, rating_count_list, events_attended_list)
        return context


class ApplicationDetailView(ActiveRequiredMixin, FormView):
    template_name = 'applications/applications_detail.html'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetailView, self).get_context_data(**kwargs)
        app_id = int(self.kwargs.get("id"))
        context['application'] = get_object_or_404(Application, pk=app_id)
        context['rushie'] = context['application'].applicant_user

        reviews = Review.objects.filter(application__pk=app_id)
        member_avg_rating_total = 0
        member_avg_rating_count = 0
        board_avg_rating_total = 0
        board_avg_rating_count = 0
        anon_avg_rating_total = 0
        anon_avg_rating_count = 0
        events_attended_count = 0

        for review in reviews:
            if review.rating is None:
                continue

            if review.reviewer_user is None:
                anon_avg_rating_count += 1
                anon_avg_rating_total += review.rating
            elif review.reviewer_user.is_board():
                board_avg_rating_count += 1
                board_avg_rating_total += review.rating
            else:
                member_avg_rating_count += 1
                member_avg_rating_total += review.rating

        avg_rating_total = member_avg_rating_total + board_avg_rating_total
        avg_rating_count = member_avg_rating_count + board_avg_rating_count

        if avg_rating_count != 0:
            context['avg_rating'] = "{0:.2f}".format(avg_rating_total / avg_rating_count)
        else:
            context['avg_rating'] = "-"

        if member_avg_rating_count != 0:
            context['member_avg_rating'] = "{0:.2f}".format(member_avg_rating_total / member_avg_rating_count)
        else:
            context['member_avg_rating'] = "-"

        if board_avg_rating_count != 0:
            context['board_avg_rating'] = "{0:.2f}".format(board_avg_rating_total / board_avg_rating_count)
        else:
            context['board_avg_rating'] = "-"

        if anon_avg_rating_count != 0:
            context['anon_avg_rating'] = "{0:.2f}".format(anon_avg_rating_total / anon_avg_rating_count)
        else:
            context['anon_avg_rating'] = "-"

        context['events_attended'] = events_attended_count

        context['reviews'] = reviews
        context['events'] = list(context['rushie'].event_attendees.all())
        print(context['events'])
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.modify_review()
        return super(ApplicationDetailView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('applications:list')

texaslan/comments/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView

from .forms import CommentForm
from .models import Comment
from texaslan.utils.utils import ActiveRequiredMixin


class CommentView(ActiveRequiredMixin, FormView):
    template_name = 'comments/comments_list.html'
    form_class = CommentForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.all()
        return context

    def form_valid(self, form):
        form.create_comment()
        return super(CommentView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully created the comment!')
        return reverse('comments:list')

texaslan/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView

from texaslan.utils.utils import OfficerRequiredMixin, EventPermissionsRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        qs = qs.filter(start_time__gte=now)

        tags = EventTag.objects.all()
        open_tag = [tag.id for tag in tags.filter(name="Open Rush")]
        closed_tag = [tag.id for tag in tags.filter(name="Closed Rush")]

        if self.request.user.is_anonymous() or self.request.user.is_open_rushie():
            qs = qs.filter(event_tags__in=open_tag)
        elif self.request.user.is_closed_rushie():
            qs = qs.filter(event_tags__in=closed_tag)

        return qs


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(start_time__year=year, start_time__month=month)

    if request.user.is_anonymous() or request.user.is_open_rushie():
        event_list = [event for event in event_list if event.is_open_rush_safe()]
    elif request.user.is_closed_rushie():
        event_list = [event for event in event_list if event.is_closed_rush_safe()]
    else:
        event_list = [event for event in event_list if event.is_member_and_pledge_safe()]

    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(EventPermissionsRequiredMixin, DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(OfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')

texaslan/templates/voting/base.html
{% extends "base.html" %}
{% load i18n %}
{% block voting_tab %}active{% endblock %}

texaslan/templates/voting/candidate_apply.html
{% extends "voting/base.html" %}
{% block title %}LAN - Applying{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <h1>Applying for {{ position }}</h1>
                <form class="form-horizontal" method="post" action="{% url 'voting:apply' position_id %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="fieldWrapper">
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <input type="hidden" name="position_id" value="{{ position_id }}"/>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

texaslan/templates/voting/candidate_detail.html
{% extends "voting/base.html" %}
{% block title %}LAN - Applying{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>
                    {{ candidate.user.full_name }} for
                    {{ position }}
                </h1>
            </div>
            <div class="panel-body">
                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="{{ candidate.user.get_gravatar_image_url }}" class="img-thumbnail"/>
                    </div>
                </div>
                <div class="col-md-9">
                    <h5>{{ candidate.description }}</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

texaslan/templates/voting/candidate_list.html
{% extends "voting/base.html" %}
{% load crispy_forms_tags %}
{% block title %}LAN - Candidates{% endblock %}

{% block content %}
    <div class="container">
        {% if not voting_closed %}
            {% if request.user.is_board and voting_open %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">Board Officer Panel</h1>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="post" action="{% url 'voting:list' %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="control-group">
                                <div class="controls">
                                    <button type="submit" class="btn btn-primary">Run Election</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}
            {% if voting_open and has_not_voted %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">Actions</h1>
                    </div>
                    <div class="panel-body">
                        <div class="control-group">
                            <div class="controls">
                                <a href="{% url 'voting:vote' %}" class="btn btn-primary">Vote</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="panel panel-default">
            <div class="panel-body">
                <div>
                    {% for position, abrev_pos, has_winner, has_applied, is_applying_open, candidates in positions %}
                        <div>
                            <h3>{{ position }}</h3>
                            {% if not has_winner and not has_applied and is_applying_open %}
                                <a class="btn btn-primary" href="{% url 'voting:apply' abrev_pos %}">Apply Here</a>
                            {% endif %}
                            {% if not candidates %}
                                <h5>No candidates yet</h5>
                            {% else %}
                                <ul>
                                    {% for candidate in candidates %}
                                        <li>
                                            <a href="{% url 'voting:candidate_detail' candidate.position candidate.user.username %}">
                                                <h5>
                                                    {{ candidate.user.full_name }}
                                                    {% if candidate.has_won %}
                                                        - Won Position
                                                    {% endif %}
                                                </h5>
                                            </a></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    {% endfor %}

                </div>
            </div>
        {% else %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Voting is Closed.</h3>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}

texaslan/templates/voting/vote.html
{% extends "voting/base.html" %}
{% load crispy_forms_tags %}
{% block title %}LAN - Vote{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="{% url 'voting:vote' %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="fieldWrapper">
                            {% if field.help_text %}
                                <h3>{{ field.help_text|safe }}</h3>
                            {% endif %}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}